version: '3.8'
services:
  postgres:
    container_name: postgres_microservices_auth
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres_microservices_auth
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  postgres:
    driver: bridge
# services:
#   postgres:
#     container_name: postgres_banhkemduyen
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: banhkemduyen
#     ports:
#       - 5432:5432
#     volumes:
#       - ./data:/var/lib/postgresql/data

# networks:
#   postgres:
#     driver: bridge
